version: "3.9"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - db-data:/app
      - ./media:/app/media
    environment:
      - DB_URL=sqlite+aiosqlite:///./db.sqlite3
      - SYNC_DB_URL=sqlite:///./app.db
      - STORAGE_PATH=./media
      - REPLICATE_API_TOKEN=dummy
      - BROKER_URL=redis://redis:6379/0
      - RESULT_BACKEND=redis://redis:6379/1
    depends_on:
      - redis
      - alembic

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  worker:
    build: .
    command: celery -A app.config.celery_app.celery worker --loglevel=info
    volumes:
      - db-data:/app
      - ./media:/app/media
    environment:
      - DB_URL=sqlite+aiosqlite:///./db.sqlite3
      - STORAGE_PATH=./media
      - REPLICATE_API_TOKEN=dummy
      - BROKER_URL=redis://redis:6379/0
      - RESULT_BACKEND=redis://redis:6379/1
    depends_on:
      - redis
      - alembic

  alembic:
    build: .
    command: alembic upgrade head
    volumes:
      - db-data:/app
    environment:
      - SYNC_DB_URL=sqlite:///./app.db
      - DB_URL=sqlite+aiosqlite:///./db.sqlite3
      - STORAGE_PATH=./media
      - REPLICATE_API_TOKEN=dummy
      - BROKER_URL=redis://redis:6379/0
      - RESULT_BACKEND=redis://redis:6379/1
    depends_on:
      - redis

volumes:
  db-data: